<a href="https://colab.research.google.com/github/nityanandkore/6162-KDD/blob/master/Homework9_TopicModeling_Mutual_Information.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 9

The corpus contains 180 documents of movie reviews written by two reviewers. Each document is a review on one movie written by one reviewer. The first 80 reviews were written by Berardinelli and the rest 100 were by Schwartz.
Problem 
Find the top ten words with the highest mutual information with the document author and their respective mutual information. Explain (in Python comments) that what it means for a word by having a high mutual information with the document author.



In [1]:

!rm 6162-KDD
!git clone https://github.com/nityanandkore/6162-KDD.git

rm: cannot remove '6162-KDD': No such file or directory
Cloning into '6162-KDD'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 138 (delta 4), reused 0 (delta 0), pack-reused 129
Receiving objects: 100% (138/138), 20.79 MiB | 36.70 MiB/s, done.
Resolving deltas: 100% (70/70), done.


In [27]:
print("Files:")
!ls /content/6162-KDD/DataSet/MovieReviews
print("File Count:")
!ls  /content/6162-KDD/DataSet/MovieReviews/ |wc -l


Files:
16748.txt  17384.txt  17803.txt  18161.txt  1865.txt  1975.txt	2055.txt
17108.txt  17391.txt  17811.txt  18181.txt  1866.txt  1976.txt	2058.txt
17109.txt  17398.txt  17874.txt  18227.txt  1867.txt  1979.txt	2059.txt
17110.txt  17399.txt  17879.txt  18263.txt  1889.txt  1981.txt	2062.txt
17111.txt  17430.txt  17886.txt  18272.txt  1891.txt  1984.txt	2067.txt
17116.txt  17431.txt  17896.txt  18273.txt  1908.txt  1985.txt	2076.txt
17117.txt  17447.txt  17898.txt  18274.txt  1910.txt  1990.txt	2079.txt
17118.txt  17457.txt  17902.txt  18282.txt  1911.txt  1991.txt	2080.txt
17119.txt  17460.txt  17912.txt  18283.txt  1912.txt  1994.txt	2081.txt
17139.txt  17501.txt  17933.txt  18307.txt  1916.txt  1998.txt	2085.txt
17144.txt  17518.txt  17934.txt  18368.txt  1917.txt  2005.txt	2086.txt
17145.txt  17532.txt  17945.txt  18375.txt  1921.txt  2006.txt	2087.txt
17146.txt  17534.txt  17963.txt  18376.txt  1925.txt  2007.txt	2089.txt
17147.txt  17578.txt  17971.txt  18396.txt  1928.txt  200

In [0]:

from zipfile import ZipFile

# Create a ZipFile Object and load sample.zip in it
with ZipFile('6162-KDD/DataSet/MovieReviews.zip', 'r') as zipObj:
# Extract all the contents of zip file in current directory
      zipObj.extractall('6162-KDD/DataSet/')

In [32]:
corpus_root = '/content/6162-KDD/DataSet/MovieReviews' 
corpus_Berardinelli = '/content/Berardinelli/'
corpus_Schwartz = '/content/Schwartz/'
print(corpus_Berardinelli)
print(corpus_Schwartz)

/content/Berardinelli/
/content/Schwartz/


In [0]:
import glob, os, shutil
os.chdir(corpus_root)
for file in glob.glob("????.txt"):
    if not os.path.exists(corpus_Berardinelli):
        os.makedirs(corpus_Berardinelli)
    shutil.copyfile(file,corpus_Berardinelli+file)




In [28]:
print("Berardinelli Files:")
!ls /content/Berardinelli/
print("File Count:")
!ls  /content/Berardinelli/ |wc -l

Berardinelli Files:
1858.txt  1910.txt  1932.txt  1975.txt	2005.txt  2035.txt  2067.txt  2091.txt
1859.txt  1911.txt  1934.txt  1976.txt	2006.txt  2036.txt  2076.txt  2094.txt
1860.txt  1912.txt  1937.txt  1979.txt	2007.txt  2043.txt  2079.txt  2095.txt
1864.txt  1916.txt  1943.txt  1981.txt	2008.txt  2045.txt  2080.txt  2098.txt
1865.txt  1917.txt  1944.txt  1984.txt	2009.txt  2046.txt  2081.txt  2099.txt
1866.txt  1921.txt  1945.txt  1985.txt	2025.txt  2051.txt  2085.txt  2101.txt
1867.txt  1925.txt  1961.txt  1990.txt	2026.txt  2055.txt  2086.txt  2108.txt
1889.txt  1928.txt  1967.txt  1991.txt	2030.txt  2058.txt  2087.txt  2110.txt
1891.txt  1929.txt  1968.txt  1994.txt	2031.txt  2059.txt  2089.txt  2113.txt
1908.txt  1930.txt  1974.txt  1998.txt	2033.txt  2062.txt  2090.txt  2115.txt
File Count:
80


In [0]:
import glob, os, shutil
os.chdir(corpus_root)
for file in glob.glob("?????.txt"):
    if not os.path.exists(corpus_Schwartz):
        os.makedirs(corpus_Schwartz)
    shutil.copyfile(file,corpus_Schwartz+file)

In [34]:
print("Schwartz Files:")
!ls /content/Schwartz/
print("File Count:")
!ls  /content/Schwartz/ |wc -l

Schwartz Files:
16748.txt  17185.txt  17430.txt  17695.txt  17912.txt  18136.txt  18376.txt
17108.txt  17192.txt  17431.txt  17711.txt  17933.txt  18141.txt  18396.txt
17109.txt  17219.txt  17447.txt  17713.txt  17934.txt  18156.txt  18406.txt
17110.txt  17239.txt  17457.txt  17753.txt  17945.txt  18161.txt  18413.txt
17111.txt  17243.txt  17460.txt  17757.txt  17963.txt  18181.txt  18414.txt
17116.txt  17254.txt  17501.txt  17758.txt  17971.txt  18227.txt  18447.txt
17117.txt  17255.txt  17518.txt  17761.txt  17992.txt  18263.txt  18473.txt
17118.txt  17280.txt  17532.txt  17803.txt  18004.txt  18272.txt  18480.txt
17119.txt  17300.txt  17534.txt  17811.txt  18016.txt  18273.txt  18485.txt
17139.txt  17303.txt  17578.txt  17874.txt  18032.txt  18274.txt  18498.txt
17144.txt  17341.txt  17609.txt  17879.txt  18067.txt  18282.txt
17145.txt  17384.txt  17610.txt  17886.txt  18068.txt  18283.txt
17146.txt  17391.txt  17655.txt  17896.txt  18080.txt  18307.txt
17147.txt  17398.txt  17662.t

In [35]:
from nltk.corpus import PlaintextCorpusReader

filelists_Berardinelli = PlaintextCorpusReader(corpus_Berardinelli, '.*',encoding='latin-1')
filelists_Berardinelli.fileids()

['1858.txt',
 '1859.txt',
 '1860.txt',
 '1864.txt',
 '1865.txt',
 '1866.txt',
 '1867.txt',
 '1889.txt',
 '1891.txt',
 '1908.txt',
 '1910.txt',
 '1911.txt',
 '1912.txt',
 '1916.txt',
 '1917.txt',
 '1921.txt',
 '1925.txt',
 '1928.txt',
 '1929.txt',
 '1930.txt',
 '1932.txt',
 '1934.txt',
 '1937.txt',
 '1943.txt',
 '1944.txt',
 '1945.txt',
 '1961.txt',
 '1967.txt',
 '1968.txt',
 '1974.txt',
 '1975.txt',
 '1976.txt',
 '1979.txt',
 '1981.txt',
 '1984.txt',
 '1985.txt',
 '1990.txt',
 '1991.txt',
 '1994.txt',
 '1998.txt',
 '2005.txt',
 '2006.txt',
 '2007.txt',
 '2008.txt',
 '2009.txt',
 '2025.txt',
 '2026.txt',
 '2030.txt',
 '2031.txt',
 '2033.txt',
 '2035.txt',
 '2036.txt',
 '2043.txt',
 '2045.txt',
 '2046.txt',
 '2051.txt',
 '2055.txt',
 '2058.txt',
 '2059.txt',
 '2062.txt',
 '2067.txt',
 '2076.txt',
 '2079.txt',
 '2080.txt',
 '2081.txt',
 '2085.txt',
 '2086.txt',
 '2087.txt',
 '2089.txt',
 '2090.txt',
 '2091.txt',
 '2094.txt',
 '2095.txt',
 '2098.txt',
 '2099.txt',
 '2101.txt',
 '2108.txt',

In [0]:
#create a list of news articles
news_Berardinelli = []
for fileid in filelists_Berardinelli.fileids():
    news_Berardinelli.append(filelists_Berardinelli.raw(fileid))

In [38]:
news_Berardinelli

['Starring: Tom Guiry, Mike Vitar, Patrick Renna, Chauncey Leopardi, Karen Allen, James Earl Jones Director: David Mickey Evans Producers: Dale DeLatorre and William S. Gilmore Screenplay: David Mickey Evans and Robert Gunter Music: David Newman Released by Twentieth Century Fox\nEight boys, led by Benjamin Rodriquez (Mike Vitar), make up a sandlot baseball team in Southern California during the late fifties. When Scotty Small (Tom Guiry) moves into town, he doesn\'t know how to catch or throw, despite the best efforts of his stepfather to teach him. That all changes, however, when Ben befriends him. Now, with their ninth man, the sandlot group is a full team. However, although their little field is a great place to play ball, it has its dark secret, for beyond the home run fence lurks The Beast, some kind of fearsome dog about which frightful stories abound.\nKids and adults will enjoy THE SANDLOT, but for different reasons. Children will find in it an adventure with a sense of humor 

In [0]:
#import the shorttext library for text preprocessing
#make sure to have shorttext installed before importing. To install shorttext, run "pip install -U shorttext" at your command terminal
#in addition, in order to use shorttext in this case, you need to download a package "en" using the command "python -m spacy download en" at your command terminal
#standard_text_preprocessor_1 under shorttext.utils provides a standar way of text preprocessing, including the following steps:

 #removing special characters,
 #removing numerals,
 #converting all alphabets to lower cases,
 #removing stop words, and
 #stemming the words (using Porter stemmer).
#!pip install shorttext
import shorttext
preprocess = shorttext.utils.standard_text_preprocessor_1()
corpus = [preprocess(article).split(' ') for article in news_Berardinelli]

In [0]:
#convert the corpus of news to a document term matrix (dtm), where each row represents a document, each column represents the number of occurence for a word
dtm = shorttext.utils.DocumentTermMatrix(corpus, docids = filelists_Berardinelli.fileids())

In [45]:
type(dtm)

shorttext.utils.dtm.DocumentTermMatrix

In [46]:
corpus

[['star',
  'tom',
  'guiri',
  'mike',
  'vitar',
  'patrick',
  'renna',
  'chauncey',
  'leopardi',
  'karen',
  'jame',
  'earl',
  'jone',
  'director',
  'david',
  'mickey',
  'evan',
  'produc',
  'dale',
  'delatorr',
  'william',
  'gilmor',
  'screenplay',
  'david',
  'mickey',
  'evan',
  'robert',
  'gunter',
  'music',
  'david',
  'newman',
  'releas',
  'twentieth',
  'centuri',
  'fox',
  '\n',
  '',
  'eight',
  'boy',
  'led',
  'benjamin',
  'rodriquez',
  'mike',
  'vitar',
  'make',
  'sandlot',
  'basebal',
  'team',
  'southern',
  'california',
  'late',
  'fifti',
  'scotti',
  'small',
  'tom',
  'guiri',
  'move',
  'town',
  'nt',
  'know',
  'catch',
  'throw',
  'despit',
  'best',
  'effort',
  'stepfath',
  'teach',
  'chang',
  'howev',
  'befriend',
  'ninth',
  'sandlot',
  'group',
  'full',
  'team',
  'howev',
  'although',
  'littl',
  'field',
  'great',
  'place',
  'play',
  'ball',
  'dark',
  'secret',
  'beyond',
  'home',
  'run',
  'fenc

In [0]:
#check number of occurence of the word "director" in each document
dtm.get_token_occurences('director')

{'16748.txt': 3.0,
 '17108.txt': 3.0,
 '17109.txt': 1.0,
 '17110.txt': 2.0,
 '17111.txt': 1.0,
 '17116.txt': 1.0,
 '17117.txt': 5.0,
 '17118.txt': 1.0,
 '17119.txt': 5.0,
 '17139.txt': 1.0,
 '17144.txt': 1.0,
 '17145.txt': 2.0,
 '17146.txt': 2.0,
 '17147.txt': 1.0,
 '17150.txt': 1.0,
 '17185.txt': 3.0,
 '17192.txt': 4.0,
 '17219.txt': 1.0,
 '17239.txt': 2.0,
 '17243.txt': 2.0,
 '17254.txt': 1.0,
 '17255.txt': 1.0,
 '17280.txt': 2.0,
 '17300.txt': 2.0,
 '17303.txt': 2.0,
 '17341.txt': 1.0,
 '17384.txt': 2.0,
 '17398.txt': 1.0,
 '17399.txt': 3.0,
 '17430.txt': 2.0,
 '17431.txt': 2.0,
 '17447.txt': 1.0,
 '17457.txt': 1.0,
 '17460.txt': 2.0,
 '17501.txt': 2.0,
 '17518.txt': 1.0,
 '17534.txt': 1.0,
 '17578.txt': 1.0,
 '17609.txt': 1.0,
 '17610.txt': 1.0,
 '17655.txt': 1.0,
 '17663.txt': 1.0,
 '17695.txt': 2.0,
 '17711.txt': 1.0,
 '17713.txt': 2.0,
 '17753.txt': 1.0,
 '17757.txt': 2.0,
 '17758.txt': 2.0,
 '17761.txt': 1.0,
 '17803.txt': 1.0,
 '17811.txt': 1.0,
 '17874.txt': 2.0,
 '17879.txt'

In [0]:
type(dtm.get_token_occurences('director'))

dict

In [0]:
# define a function to calculate entropy given a distribution
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0
    
    p = p/sum(p)

    p = p[ p > 0 ]
    
    H = -sum(p*np.log2(p))
    
    return H

In [0]:
entropy(np.array( [12,45]))

0.7424875695421236

In [0]:
entropy( np.array( [100,60,40]))

1.4854752972273344

In [0]:
dtm.get_token_occurences('director').values()

dict_values([3.0, 3.0, 1.0, 2.0, 1.0, 1.0, 5.0, 1.0, 5.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 3.0, 4.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 3.0, 2.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 3.0, 3.0, 2.0, 1.0, 1.0, 2.0, 1.0, 4.0, 1.0, 2.0, 4.0, 2.0, 1.0, 1.0, 1.0, 8.0, 3.0, 2.0, 1.0, 2.0, 2.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 3.0, 2.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 2.0])

In [0]:
#convert the distribution of word "director" from dictionary values to a list
director_dis = list(dtm.get_token_occurences('director').values())

director_dis

[3.0,
 3.0,
 1.0,
 2.0,
 1.0,
 1.0,
 5.0,
 1.0,
 5.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 3.0,
 4.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 3.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 3.0,
 3.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 4.0,
 1.0,
 2.0,
 4.0,
 2.0,
 1.0,
 1.0,
 1.0,
 8.0,
 3.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 3.0,
 2.0,
 1.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 1.0,
 2.0]

In [0]:
#calculate the entropy for the word "director"
entropy(director_dis)

7.146642117134532

In [0]:
dtm.get_token_occurences('director').keys()

dict_keys(['16748.txt', '17108.txt', '17109.txt', '17110.txt', '17111.txt', '17116.txt', '17117.txt', '17118.txt', '17119.txt', '17139.txt', '17144.txt', '17145.txt', '17146.txt', '17147.txt', '17150.txt', '17185.txt', '17192.txt', '17219.txt', '17239.txt', '17243.txt', '17254.txt', '17255.txt', '17280.txt', '17300.txt', '17303.txt', '17341.txt', '17384.txt', '17398.txt', '17399.txt', '17430.txt', '17431.txt', '17447.txt', '17457.txt', '17460.txt', '17501.txt', '17518.txt', '17534.txt', '17578.txt', '17609.txt', '17610.txt', '17655.txt', '17663.txt', '17695.txt', '17711.txt', '17713.txt', '17753.txt', '17757.txt', '17758.txt', '17761.txt', '17803.txt', '17811.txt', '17874.txt', '17879.txt', '17886.txt', '17896.txt', '17898.txt', '17902.txt', '17912.txt', '17933.txt', '17934.txt', '17945.txt', '17963.txt', '17971.txt', '17992.txt', '18004.txt', '18016.txt', '18032.txt', '18067.txt', '18068.txt', '18080.txt', '18087.txt', '18088.txt', '18136.txt', '18141.txt', '18156.txt', '18161.txt', '

In [0]:
#convert the documents that contain the word "director" from dictionary keys to a list
director_docs = list(dtm.get_token_occurences('director').keys())

In [0]:
director_docs

['16748.txt',
 '17108.txt',
 '17109.txt',
 '17110.txt',
 '17111.txt',
 '17116.txt',
 '17117.txt',
 '17118.txt',
 '17119.txt',
 '17139.txt',
 '17144.txt',
 '17145.txt',
 '17146.txt',
 '17147.txt',
 '17150.txt',
 '17185.txt',
 '17192.txt',
 '17219.txt',
 '17239.txt',
 '17243.txt',
 '17254.txt',
 '17255.txt',
 '17280.txt',
 '17300.txt',
 '17303.txt',
 '17341.txt',
 '17384.txt',
 '17398.txt',
 '17399.txt',
 '17430.txt',
 '17431.txt',
 '17447.txt',
 '17457.txt',
 '17460.txt',
 '17501.txt',
 '17518.txt',
 '17534.txt',
 '17578.txt',
 '17609.txt',
 '17610.txt',
 '17655.txt',
 '17663.txt',
 '17695.txt',
 '17711.txt',
 '17713.txt',
 '17753.txt',
 '17757.txt',
 '17758.txt',
 '17761.txt',
 '17803.txt',
 '17811.txt',
 '17874.txt',
 '17879.txt',
 '17886.txt',
 '17896.txt',
 '17898.txt',
 '17902.txt',
 '17912.txt',
 '17933.txt',
 '17934.txt',
 '17945.txt',
 '17963.txt',
 '17971.txt',
 '17992.txt',
 '18004.txt',
 '18016.txt',
 '18032.txt',
 '18067.txt',
 '18068.txt',
 '18080.txt',
 '18087.txt',
 '1808

In [0]:
director_docs[1]

'17108.txt'

In [0]:
[int(i) for i in director_docs[1].split('.') if i.isdigit()]

[17108]

In [0]:
#print the number of "Berardinelli" documents that contain the word "director"
sub = 9999
count_Berardinelli = 0
for item in director_docs:
    filelist= [int(i) for i in item.split('.') if i.isdigit()]
    for x in filelist:
        if sub >= x:
         count_Berardinelli += 1
print(count_Berardinelli)

68


In [0]:
#print the number of "Schwartz" documents that contain the word "director"
sub = 9999
count_Schwartz = 0
for item in director_docs:
    filelist= [int(i) for i in item.split('.') if i.isdigit()]
    for x in filelist:
        if sub < x:
         count_Schwartz += 1
print(count_Schwartz)

96


In [0]:
#this is an important step
#make an array, rows represent "Berardinelli" and "Schwartz" respectively. Columns represent the number of documents 
#that contains the word "director" and the number of documents that do NOT contain the word "director"
array = np.reshape((count_Berardinelli,80-count_Berardinelli,count_Schwartz,100-count_Schwartz,),(2,2))

In [0]:
array

array([[68, 12],
       [96,  4]])

In [0]:
#calculate the column sum of the array
np.sum(array, axis = 0)

array([164,  16])

In [0]:
#calculate the row sum of the array
np.sum(array, axis = 1)

array([ 80, 100])

In [0]:
#calculate the entropy of the document class (Berardinelli, Schwartz)
marginal_entropy = entropy(np.sum(array, axis = 1))

In [0]:
#calculate the column probabilities
column_probs = np.sum(array, axis = 0)/180

In [0]:
column_probs

array([0.91111111, 0.08888889])

In [0]:
#calculate the column entropies
column_entropy = np.apply_along_axis(entropy, 0, array)

In [0]:
column_entropy

array([0.97886985, 0.81127812])

In [0]:
conditional_entropy = sum(column_probs*column_entropy)

In [0]:
conditional_entropy

0.963972808191432

In [0]:
#calculate the mutual information between the word "director" and the document class (Berardinelli, Schwartz)
MI_associ = marginal_entropy - conditional_entropy

In [0]:
MI_associ

0.027103251646790172