<a href="https://colab.research.google.com/github/nityanandkore/6162-KDD/blob/master/Homework9_TopicModeling_Mutual_Information.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 9

The corpus contains 180 documents of movie reviews written by two reviewers. Each document is a review on one movie written by one reviewer. The first 80 reviews were written by Berardinelli and the rest 100 were by Schwartz.
Problem 
Find the top ten words with the highest mutual information with the document author and their respective mutual information. Explain (in Python comments) that what it means for a word by having a high mutual information with the document author.

=> 
schwartz is the highest MI word as it matches with Document author name.
Remaining words MI shows that their occurance is highly dependent on author.

Final Top 10 Word List with Mutual Information:

(0.9910760598382222, 'schwartz')
(0.8693518353671907, 'reserv')
(0.8062750920498906, 'denni')
(0.6435687623487039, 'review')
(0.4906222103533695, 'right')
(0.42390238621265564, 'howev')
(0.4189567759226782, 'releas')
(0.39200421823950693, 'cast')
(0.3852456598043049, 'screenplay')
(0.37245646603838223, 'produc')


In [0]:

!rm 6162-KDD
!git clone https://github.com/nityanandkore/6162-KDD.git

rm: cannot remove '6162-KDD': Is a directory
fatal: destination path '6162-KDD' already exists and is not an empty directory.


In [0]:

from zipfile import ZipFile

# Create a ZipFile Object and load sample.zip in it
with ZipFile('6162-KDD/DataSet/MovieReviews.zip', 'r') as zipObj:
# Extract all the contents of zip file in current directory
      zipObj.extractall('6162-KDD/DataSet/')

In [0]:
print("Files:")
!ls /content/6162-KDD/DataSet/MovieReviews
print("File Count:")
!ls  /content/6162-KDD/DataSet/MovieReviews/ |wc -l


In [0]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = '6162-KDD/DataSet/MovieReviews' 
filelists = PlaintextCorpusReader(corpus_root, '.*',encoding='latin-1')
filelists.fileids()

In [0]:
#create a list of news articles
news = []
for fileid in filelists.fileids():
    news.append(filelists.raw(fileid))

In [0]:
news

In [0]:
#import the shorttext library for text preprocessing
#make sure to have shorttext installed before importing. To install shorttext, run "pip install -U shorttext" at your command terminal
#in addition, in order to use shorttext in this case, you need to download a package "en" using the command "python -m spacy download en" at your command terminal
#standard_text_preprocessor_1 under shorttext.utils provides a standar way of text preprocessing, including the following steps:

 #removing special characters,
 #removing numerals,
 #converting all alphabets to lower cases,
 #removing stop words, and
 #stemming the words (using Porter stemmer).
!pip install shorttext
import shorttext
preprocess = shorttext.utils.standard_text_preprocessor_1()
corpus = [preprocess(article).split(' ') for article in news]

In [0]:
#convert the corpus of news to a document term matrix (dtm), where each row represents a document, each column represents the number of occurence for a word
dtm = shorttext.utils.DocumentTermMatrix(corpus, docids = filelists.fileids())

In [0]:
type(dtm)

shorttext.utils.dtm.DocumentTermMatrix

In [0]:
corpus

[['denni',
  'schwartz',
  'movi',
  'review',
  'poetri',
  '\n',
  '',
  'unmad',
  'bed',
  'director',
  'nichola',
  'barker',
  'cast',
  'brenda',
  'mont',
  'michael',
  'stephano',
  'aime',
  'copp',
  'mikey',
  'russo',
  '\n',
  '',
  'whether',
  'stori',
  'entir',
  'true',
  'part',
  'made',
  'director',
  'state',
  'unimport',
  'film',
  'cover',
  'intrigu',
  'subject',
  'matter',
  'four',
  'singl',
  'new',
  'yorker',
  'exist',
  'period',
  'nine',
  'month',
  'featur',
  'real',
  'live',
  'two',
  'femal',
  'two',
  'male',
  'actor',
  'play',
  'concern',
  'get',
  'older',
  'still',
  'singl',
  'singl',
  'scene',
  'provoc',
  'portray',
  'sad',
  'lurid',
  'comic',
  'film',
  'highlight',
  'problem',
  'found',
  'urban',
  'area',
  'across',
  'america',
  'bear',
  'wit',
  'plight',
  'singl',
  'tri',
  'search',
  'mate',
  'internet',
  'person',
  'face',
  'agon',
  'loneli',
  'unresolv',
  'psycholog',
  'problem',
  'four',
 

In [0]:
type(corpus)

list

In [0]:
len(corpus)

180

In [0]:
for review in corpus:
  for actual_word in review:
    print(actual_word)
    print(dtm.get_token_occurences(actual_word))

In [0]:
# define a function to calculate entropy given a distribution
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0
    
    p = p/sum(p)

    p = p[ p > 0 ]
    
    H = -sum(p*np.log2(p))
    
    return H

In [0]:
for review in corpus:
  for actual_word in review:
    print(actual_word)
    print(dtm.get_token_occurences(actual_word).values())


In [0]:
#convert the distribution of each word from dictionary values to a list
each_word_dis=[]
for review in corpus:
  for actual_word in review:
    each_word_dis.append([actual_word,list(dtm.get_token_occurences(actual_word).values())])
    #each_word_dis.append([actual_word])
    #each_word_dis.append(list(dtm.get_token_occurences(actual_word).values()))



In [0]:
each_word_dis[0][0]

'denni'

In [0]:
each_word_dis[0][1]

In [0]:
len(each_word_dis)

85276

In [0]:
#calculate the entropy for the each word
i=0
for word in each_word_dis:
  print(each_word_dis[i][0])
  i=i+1
  print(entropy(each_word_dis[i][1]))

Streaming output truncated to the last 5000 lines.
begin
5.918412976882335
keep
7.202506302601761
film
2.321928094887362
collaps
-0.0
nether
2.2516291673878226
region
2.75
inhabit
2.584962500721156
nightmar
2.521640636343318
split
4.707714802597437
second
5.731186661230556
anoth
3.084962500721156
scienc
3.095795255000934
fiction
-0.0
gorefest
6.749834439534081
take
5.871934970115317
place
1.584962500721156
dreari
-0.0
nearfutur
2.9139770731827523
earth
7.439019095928142


7.361046851556412

4.519902579793959
earli
4.927798970294787
minut
0.4394969869215134
fortress
1.0
brim
4.08746284125034
promis
6.668275270321539
scene
-0.0
bristl
3.334679141051595
potenti
6.185300864865373
interest
6.591508901835563
charact
4.926427859887888
strong
3.906890595608518
interact
5.169982336350698
intellig
5.87059885877521
plot
4.373551149096553
twist
2.321928094887362
ala
6.1700205294930655
littl
5.737018922113596
noth
6.3816600604487155
come
3.521640636343319
instanc
6.55057692627465
becom
3.5849625007

IndexError: ignored

In [0]:
i=0
for word in each_word_dis:
  print(dtm.get_token_occurences(each_word_dis[i][0]).keys())
  i=i+1


In [0]:
#convert the documents that contain the word from dictionary keys to a list
each_word_docs=[]

for review in corpus:
  for actual_word in review:
    each_word_docs.append([actual_word,list(dtm.get_token_occurences(actual_word).keys())])


In [0]:
each_word_docs[0][1]

['16748.txt',
 '17108.txt',
 '17109.txt',
 '17110.txt',
 '17111.txt',
 '17116.txt',
 '17117.txt',
 '17118.txt',
 '17119.txt',
 '17139.txt',
 '17144.txt',
 '17145.txt',
 '17146.txt',
 '17147.txt',
 '17150.txt',
 '17185.txt',
 '17192.txt',
 '17219.txt',
 '17239.txt',
 '17243.txt',
 '17254.txt',
 '17255.txt',
 '17280.txt',
 '17300.txt',
 '17303.txt',
 '17341.txt',
 '17384.txt',
 '17391.txt',
 '17398.txt',
 '17399.txt',
 '17430.txt',
 '17431.txt',
 '17447.txt',
 '17457.txt',
 '17460.txt',
 '17501.txt',
 '17518.txt',
 '17532.txt',
 '17534.txt',
 '17578.txt',
 '17609.txt',
 '17610.txt',
 '17655.txt',
 '17662.txt',
 '17663.txt',
 '17695.txt',
 '17711.txt',
 '17713.txt',
 '17753.txt',
 '17757.txt',
 '17758.txt',
 '17761.txt',
 '17803.txt',
 '17811.txt',
 '17874.txt',
 '17879.txt',
 '17886.txt',
 '17896.txt',
 '17898.txt',
 '17902.txt',
 '17912.txt',
 '17933.txt',
 '17934.txt',
 '17945.txt',
 '17963.txt',
 '17971.txt',
 '17992.txt',
 '18004.txt',
 '18016.txt',
 '18032.txt',
 '18067.txt',
 '1806

In [0]:
each_word_docs[1]

In [0]:
each_word_docs

In [0]:
type(each_word_docs)

list

In [0]:
#print the number of Berardinelli reviews that contain the word 
import re
sub = 9999
count_Berardinelli= []
count_B = 0
for word_and_file in each_word_docs:
    #print(word_and_file[0])
    for file in word_and_file[1]:
      filelist= [int(i) for i in file.split('.') if i.isdigit()]
      #print(filelist)
      for x in filelist:
        if sub >= x:
          count_B += 1
    count_Berardinelli.append([word_and_file[0],count_B])
    count_B=0
    
count_Berardinelli


[['denni', 6],
 ['schwartz', 0],
 ['movi', 79],
 ['review', 9],
 ['poetri', 1],
 ['\n', 80],
 ['', 80],
 ['unmad', 0],
 ['bed', 0],
 ['director', 68],
 ['nichola', 2],
 ['barker', 0],
 ['cast', 24],
 ['brenda', 4],
 ['mont', 0],
 ['michael', 20],
 ['stephano', 0],
 ['aime', 0],
 ['copp', 0],
 ['mikey', 2],
 ['russo', 2],
 ['\n', 80],
 ['', 80],
 ['whether', 22],
 ['stori', 65],
 ['entir', 29],
 ['true', 26],
 ['part', 47],
 ['made', 37],
 ['director', 68],
 ['state', 11],
 ['unimport', 0],
 ['film', 80],
 ['cover', 10],
 ['intrigu', 11],
 ['subject', 12],
 ['matter', 14],
 ['four', 9],
 ['singl', 5],
 ['new', 37],
 ['yorker', 0],
 ['exist', 6],
 ['period', 4],
 ['nine', 0],
 ['month', 8],
 ['featur', 15],
 ['real', 36],
 ['live', 35],
 ['two', 50],
 ['femal', 9],
 ['two', 50],
 ['male', 9],
 ['actor', 40],
 ['play', 50],
 ['concern', 11],
 ['get', 61],
 ['older', 6],
 ['still', 24],
 ['singl', 5],
 ['singl', 5],
 ['scene', 63],
 ['provoc', 0],
 ['portray', 17],
 ['sad', 5],
 ['lurid', 

In [0]:
len(count_Berardinelli)

85276

In [0]:
#print the number of "Schwartz" documents that contain the word "director"

import re
sub = 9999
Count_Schwartz= []
count_S = 0
for word_and_file in each_word_docs:
    #print(word_and_file[0])
    for file in word_and_file[1]:
      filelist= [int(i) for i in file.split('.') if i.isdigit()]
      #print(filelist)
      for x in filelist:
        if sub <= x:
          count_S += 1
    Count_Schwartz.append([word_and_file[0],count_S])
    count_S=0

Count_Schwartz

[['denni', 100],
 ['schwartz', 100],
 ['movi', 90],
 ['review', 97],
 ['poetri', 4],
 ['\n', 100],
 ['', 100],
 ['unmad', 2],
 ['bed', 9],
 ['director', 96],
 ['nichola', 2],
 ['barker', 1],
 ['cast', 96],
 ['brenda', 1],
 ['mont', 1],
 ['michael', 9],
 ['stephano', 1],
 ['aime', 1],
 ['copp', 1],
 ['mikey', 1],
 ['russo', 2],
 ['\n', 100],
 ['', 100],
 ['whether', 13],
 ['stori', 85],
 ['entir', 8],
 ['true', 24],
 ['part', 57],
 ['made', 58],
 ['director', 96],
 ['state', 26],
 ['unimport', 2],
 ['film', 100],
 ['cover', 20],
 ['intrigu', 10],
 ['subject', 26],
 ['matter', 31],
 ['four', 6],
 ['singl', 9],
 ['new', 41],
 ['yorker', 2],
 ['exist', 8],
 ['period', 11],
 ['nine', 3],
 ['month', 6],
 ['featur', 13],
 ['real', 47],
 ['live', 67],
 ['two', 47],
 ['femal', 8],
 ['two', 47],
 ['male', 9],
 ['actor', 30],
 ['play', 69],
 ['concern', 24],
 ['get', 88],
 ['older', 18],
 ['still', 46],
 ['singl', 9],
 ['singl', 9],
 ['scene', 56],
 ['provoc', 2],
 ['portray', 14],
 ['sad', 9],
 

In [0]:
len(Count_Schwartz)

85276

In [0]:
print(count_Berardinelli[0][0])
print(count_Berardinelli[0][1])
print(Count_Schwartz[0][0])
print(Count_Schwartz[0][1])

denni
6
denni
100


In [0]:
#this is an important step
#make an array, rows represent "Berardinelli" and "Schwartz" respectively. Columns represent the number of documents 
#that contains the word and the number of documents that do NOT contain the word 
array=[]
i=0
for word in count_Berardinelli:
  array.append(np.reshape((count_Berardinelli[i][1],80-count_Berardinelli[i][1],Count_Schwartz[i][1],100-Count_Schwartz[i][1],),(2,2)))
  i=i+1

In [0]:
array[0]

array([[  6,  74],
       [100,   0]])

In [0]:
len(array)

85276

In [0]:
type(array)

list

In [0]:
np.sum(np.array(array[0]), axis = 0)

array([106,  74])

In [0]:
#calculate the column sum of the array
i=0
for item in array:
  print(np.sum(np.array(array[i]), axis = 0))
  i=i+1

Streaming output truncated to the last 5000 lines.
[83 97]
[  6 174]
[  7 173]
[82 98]
[ 40 140]
[104  76]
[169  11]
[ 67 113]
[ 69 111]
[  2 178]
[ 22 158]
[81 99]
[ 46 134]
[ 22 158]
[109  71]
[ 10 170]
[ 36 144]
[  2 178]
[ 57 123]
[  8 172]
[ 49 131]
[119  61]
[ 56 124]
[ 10 170]
[  1 179]
[  5 175]
[ 13 167]
[  3 177]
[ 72 108]
[  4 176]
[ 52 128]
[96 84]
[ 72 108]
[ 53 127]
[ 13 167]
[ 21 159]
[ 33 147]
[  1 179]
[ 22 158]
[97 83]
[ 12 168]
[ 28 152]
[  1 179]
[180   0]
[180   0]
[ 22 158]
[ 18 162]
[ 38 142]
[ 12 168]
[  9 171]
[101  79]
[96 84]
[180   0]
[ 11 169]
[  2 178]
[ 28 152]
[ 11 169]
[ 77 103]
[ 30 150]
[  6 174]
[149  31]
[  8 172]
[ 34 146]
[ 56 124]
[ 55 125]
[111  69]
[  6 174]
[ 39 141]
[ 18 162]
[  5 175]
[ 38 142]
[ 22 158]
[ 56 124]
[95 85]
[ 11 169]
[146  34]
[93 87]
[ 16 164]
[101  79]
[180   0]
[88 92]
[ 24 156]
[  1 179]
[  1 179]
[  7 173]
[  1 179]
[  1 179]
[  2 178]
[  2 178]
[ 10 170]
[  7 173]
[  1 179]
[164  16]
[  1 179]
[  1 179]
[ 68 112]
[  8 17

In [0]:
np.sum(np.array(array[0]), axis = 1)

array([ 80, 100])

In [0]:
#calculate the row sum of the array
i=0
for item in array:
  print(np.sum(array[i], axis = 1))
  i=i+1

Streaming output truncated to the last 5000 lines.
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]
[ 80 100]

In [0]:
marginal_entropy = entropy(np.sum(array[0], axis = 1))

marginal_entropy

0.9910760598382222

In [0]:
#calculate the entropy of the document class (Berardinelli, Schwartz)
marginal_entropy=[]
i=0
for item in array:
  marginal_entropy.append(entropy(np.sum(array[i], axis = 1)))
  i+=1

marginal_entropy

In [0]:
#calculate the column probabilities
column_probs=[]
i=0
for item in array:
  column_probs.append(np.sum(array[i], axis = 0)/180)
  i+=1

column_probs


[array([0.58888889, 0.41111111]),
 array([0.55555556, 0.44444444]),
 array([0.93888889, 0.06111111]),
 array([0.58888889, 0.41111111]),
 array([0.02777778, 0.97222222]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.01111111, 0.98888889]),
 array([0.05, 0.95]),
 array([0.91111111, 0.08888889]),
 array([0.02222222, 0.97777778]),
 array([0.00555556, 0.99444444]),
 array([0.66666667, 0.33333333]),
 array([0.02777778, 0.97222222]),
 array([0.00555556, 0.99444444]),
 array([0.16111111, 0.83888889]),
 array([0.00555556, 0.99444444]),
 array([0.00555556, 0.99444444]),
 array([0.00555556, 0.99444444]),
 array([0.01666667, 0.98333333]),
 array([0.02222222, 0.97777778]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.19444444, 0.80555556]),
 array([0.83333333, 0.16666667]),
 array([0.20555556, 0.79444444]),
 array([0.27777778, 0.72222222]),
 array([0.57777778, 0.42222222]),
 array([0.52777778, 0.47222222]),
 array([0.91111111, 0.08888889]),
 array([0.20555556, 0.79444444]),
 array([0.01111111, 0.

In [0]:
#calculate the column entropies
column_entropy=[]
i=0
for item in array:
  column_entropy.append(np.apply_along_axis(entropy, 0, array[i]))
  i+=1


column_entropy 

[array([ 0.31381296, -0.        ]),
 array([-0., -0.]),
 array([0.99694182, 0.43949699]),
 array([0.419233  , 0.24476508]),
 array([0.72192809, 0.99318209]),
 array([0.99107606, 0.        ]),
 array([0.99107606, 0.        ]),
 array([-0.        ,  0.99261089]),
 array([-0.        ,  0.99701298]),
 array([0.97886985, 0.81127812]),
 array([1.        , 0.99066493]),
 array([-0.        ,  0.99185738]),
 array([0.72192809, 0.35335934]),
 array([0.72192809, 0.9875037 ]),
 array([-0.        ,  0.99185738]),
 array([0.8935711 , 0.96937992]),
 array([-0.        ,  0.99185738]),
 array([-0.        ,  0.99185738]),
 array([-0.        ,  0.99185738]),
 array([0.91829583, 0.98982206]),
 array([1.        , 0.99066493]),
 array([0.99107606, 0.        ]),
 array([0.99107606, 0.        ]),
 array([0.95176268, 0.97095059]),
 array([0.98713777, 1.        ]),
 array([0.75319799, 0.9398616 ]),
 array([0.99884554, 0.97924154]),
 array([0.99332042, 0.98747501]),
 array([0.96445906, 0.99990016]),
 array([0.97

In [0]:
len(column_entropy)

85276

In [0]:
sum(column_probs[0]*column_entropy[0])

0.1848009677883317

In [0]:
conditional_entropy=[]
i=0
for item in array:
  conditional_entropy.append(sum(column_probs[i]*column_entropy[i]))
  i+=1

conditional_entropy 

[0.1848009677883317,
 0.0,
 0.9628757434009108,
 0.34750729748951836,
 0.9856472548326234,
 0.9910760598382222,
 0.9910760598382222,
 0.9815818799874411,
 0.9471623344245454,
 0.963972808191432,
 0.9908723726978809,
 0.9863470619523976,
 0.5990718415987153,
 0.9801266035305582,
 0.9863470619523976,
 0.9571662755081444,
 0.9863470619523976,
 0.9863470619523976,
 0.9863470619523976,
 0.9886299522650962,
 0.9908723726978809,
 0.9910760598382222,
 0.9910760598382222,
 0.9672196102397002,
 0.9892814786434886,
 0.9014918579504988,
 0.9846870908606632,
 0.990852358228487,
 0.9811951328254236,
 0.963972808191432,
 0.97421365909259,
 0.9815818799874411,
 0.9910760598382222,
 0.9837089989937787,
 0.9886614490406567,
 0.9778185085479636,
 0.9733457833919241,
 0.9846890373602738,
 0.9891657498872551,
 0.9890779270566472,
 0.9815818799874411,
 0.9910138360793421,
 0.982277833899751,
 0.9767799393419452,
 0.9871321519251368,
 0.9866214033632613,
 0.9907892616737961,
 0.9516526740274389,
 0.973749061

In [0]:
len(conditional_entropy)

85276

In [0]:
#calculate the mutual information between the word "director" and the document class (Berardinelli, Schwartz)
MI_associ=[]
i=0
for item in array:
  MI_associ.append(marginal_entropy[i] - conditional_entropy[i])
  i+=1

MI_associ 

[0.8062750920498906,
 0.9910760598382222,
 0.028200316437311468,
 0.6435687623487039,
 0.005428805005598836,
 0.0,
 0.0,
 0.00949417985078116,
 0.043913725413676774,
 0.027103251646790172,
 0.0002036871403413576,
 0.004728997885824593,
 0.39200421823950693,
 0.010949456307663974,
 0.004728997885824593,
 0.03390978433007785,
 0.004728997885824593,
 0.004728997885824593,
 0.004728997885824593,
 0.002446107573126022,
 0.0002036871403413576,
 0.0,
 0.0,
 0.023856449598522067,
 0.0017945811947336354,
 0.08958420188772342,
 0.006388968977559029,
 0.00022370160973517184,
 0.009880927012798635,
 0.027103251646790172,
 0.016862400745632278,
 0.00949417985078116,
 0.0,
 0.007367060844443496,
 0.002414610797565553,
 0.013257551290258629,
 0.0177302764462981,
 0.006387022477948423,
 0.0019103099509670818,
 0.0019981327815750127,
 0.00949417985078116,
 6.222375888009779e-05,
 0.008798225938471238,
 0.014296120496277043,
 0.003943907913085409,
 0.004454656474960905,
 0.0002867981644261164,
 0.039423

In [0]:
len(MI_associ)

85276

In [0]:
word_with_MI=[]
i=0

for item in MI_associ:
  word_with_MI.append([MI_associ[i],each_word_dis[i][0]])
  i+=1

word_with_MI

[[0.8062750920498906, 'denni'],
 [0.9910760598382222, 'schwartz'],
 [0.028200316437311468, 'movi'],
 [0.6435687623487039, 'review'],
 [0.005428805005598836, 'poetri'],
 [0.0, '\n'],
 [0.0, ''],
 [0.00949417985078116, 'unmad'],
 [0.043913725413676774, 'bed'],
 [0.027103251646790172, 'director'],
 [0.0002036871403413576, 'nichola'],
 [0.004728997885824593, 'barker'],
 [0.39200421823950693, 'cast'],
 [0.010949456307663974, 'brenda'],
 [0.004728997885824593, 'mont'],
 [0.03390978433007785, 'michael'],
 [0.004728997885824593, 'stephano'],
 [0.004728997885824593, 'aime'],
 [0.004728997885824593, 'copp'],
 [0.002446107573126022, 'mikey'],
 [0.0002036871403413576, 'russo'],
 [0.0, '\n'],
 [0.0, ''],
 [0.023856449598522067, 'whether'],
 [0.0017945811947336354, 'stori'],
 [0.08958420188772342, 'entir'],
 [0.006388968977559029, 'true'],
 [0.00022370160973517184, 'part'],
 [0.009880927012798635, 'made'],
 [0.027103251646790172, 'director'],
 [0.016862400745632278, 'state'],
 [0.00949417985078116, 

In [0]:
word_with_MI[0]

['denni', 0.8062750920498906]

In [0]:
type(word_with_MI)

list

In [0]:
word_with_MI.sort(reverse=True)
word_with_MI

In [0]:
len(word_with_MI)

85276

In [0]:
 final_list=list(set( tuple(x) for x in word_with_MI))

In [0]:
len(final_list)

10930

In [0]:
final_list.sort(reverse=True)
final_list

[(0.9910760598382222, 'schwartz'),
 (0.8693518353671907, 'reserv'),
 (0.8062750920498906, 'denni'),
 (0.6435687623487039, 'review'),
 (0.4906222103533695, 'right'),
 (0.42390238621265564, 'howev'),
 (0.4189567759226782, 'releas'),
 (0.39200421823950693, 'cast'),
 (0.3852456598043049, 'screenplay'),
 (0.37245646603838223, 'produc'),
 (0.3160334896979371, 'music'),
 (0.29995861408553093, 'although'),
 (0.2525825977058259, 'ozus'),
 (0.23796338014277585, 'pictur'),
 (0.1917501564252947, 'filmmak'),
 (0.18067091153873216, 'star'),
 (0.1476165632065718, 'think'),
 (0.14007370552826837, 'moment'),
 (0.1348426973468856, 'often'),
 (0.13206860651566876, 'motion'),
 (0.13126520773852746, 'world'),
 (0.13061142961974015, 'yearold'),
 (0.1285733667432558, 'audienc'),
 (0.12014796187227028, 'viewer'),
 (0.11819801288621667, 'rate'),
 (0.11809013182776129, 'occasion'),
 (0.11467319613747162, 'perhap'),
 (0.11108848436649454, 'length'),
 (0.10671835120847117, 'script'),
 (0.10671835120847117, 'produ

In [0]:
i=0
for item in [0,1,2,3,4,5,6,7,8,9]:
  print(final_list[i])
  i+=1

(0.9910760598382222, 'schwartz')
(0.8693518353671907, 'reserv')
(0.8062750920498906, 'denni')
(0.6435687623487039, 'review')
(0.4906222103533695, 'right')
(0.42390238621265564, 'howev')
(0.4189567759226782, 'releas')
(0.39200421823950693, 'cast')
(0.3852456598043049, 'screenplay')
(0.37245646603838223, 'produc')
