In [3]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = '/Users/xniu2/Desktop/PyData/HealthNews' 
filelists = PlaintextCorpusReader(corpus_root, '.*',encoding='latin-1')
filelists.fileids()

['.DS_Store',
 'Dentistry00500.txt',
 'Dentistry00501.txt',
 'Dentistry00502.txt',
 'Dentistry00503.txt',
 'Dentistry00504.txt',
 'Dentistry00505.txt',
 'Dentistry00506.txt',
 'Dentistry00507.txt',
 'Dentistry00508.txt',
 'Dentistry00509.txt',
 'Dentistry00510.txt',
 'Dentistry00511.txt',
 'Dentistry00512.txt',
 'Dentistry00513.txt',
 'Dentistry00514.txt',
 'Dentistry00515.txt',
 'Dentistry00516.txt',
 'Dentistry00517.txt',
 'Dentistry00518.txt',
 'Dentistry00519.txt',
 'Dentistry00520.txt',
 'Dentistry00521.txt',
 'Dentistry00522.txt',
 'Dentistry00523.txt',
 'Dentistry00524.txt',
 'Dentistry00525.txt',
 'Dentistry00526.txt',
 'Dentistry00527.txt',
 'Dentistry00528.txt',
 'Dentistry00529.txt',
 'Dentistry00530.txt',
 'Dentistry00531.txt',
 'Dentistry00532.txt',
 'Dentistry00533.txt',
 'Dentistry00534.txt',
 'Dentistry00535.txt',
 'Dentistry00536.txt',
 'Dentistry00537.txt',
 'Dentistry00538.txt',
 'Dentistry00539.txt',
 'Dentistry00540.txt',
 'Dentistry00541.txt',
 'Dentistry00542.txt

In [4]:
#create a list of news articles
news = []
for fileid in filelists.fileids():
    news.append(filelists.raw(fileid))

In [16]:
news

['\x00\x00\x00\x01Bud1\x00\x00\x10\x00\x00\x00\x08\x00\x00\x00\x10\x00\x00\x00\x00%\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

In [20]:
#import the shorttext library for text preprocessing
#make sure to have shorttext installed before importing. To install shorttext, run "pip install -U shorttext" at your command terminal
#in addition, in order to use shorttext in this case, you need to download a package "en" using the command "python -m spacy download en" at your command terminal
#standard_text_preprocessor_1 under shorttext.utils provides a standar way of text preprocessing, including the following steps:

 #removing special characters,
 #removing numerals,
 #converting all alphabets to lower cases,
 #removing stop words, and
 #stemming the words (using Porter stemmer).

import shorttext
preprocess = shorttext.utils.standard_text_preprocessor_1()
corpus = [preprocess(article).split(' ') for article in news]

In [21]:
#convert the corpus of news to a document term matrix (dtm), where each row represents a document, each column represents the number of occurence for a word
dtm = shorttext.utils.DocumentTermMatrix(corpus, docids = filelists.fileids())

In [61]:
type(dtm)

shorttext.utils.dtm.DocumentTermMatrix

In [84]:
corpus

[['bud', '\x0b', '', '', '', '\x0b', '', 'edsdb', '', '', ''],
 ['novel',
  'dental',
  'biomateri',
  'technolog',
  'jdr',
  'publish',
  'special',
  'issu',
  '\n',
  '',
  '',
  'pthe',
  'intern',
  'american',
  'associ',
  'dental',
  'research',
  'iadraadr',
  'publish',
  'special',
  'theme',
  'issu',
  'emjourn',
  'dental',
  'research',
  'jdrem',
  'center',
  'novel',
  'dental',
  'biomateri',
  'technolog',
  'although',
  'associ',
  'publish',
  'clinic',
  'supplement',
  'jdr',
  'first',
  'special',
  'theme',
  'issu',
  'associ',
  'publishedppthi',
  'special',
  'theme',
  'issu',
  'jdr',
  'contain',
  'collect',
  'time',
  'articl',
  'design',
  'provid',
  'reader',
  'review',
  'import',
  'new',
  'materi',
  'develop',
  'well',
  'exampl',
  'novel',
  'stateoftheart',
  'research',
  'work',
  'critic',
  'area',
  'themat',
  'issu',
  'cover',
  'sever',
  'area',
  'materi',
  'developmentppthi',
  'issu',
  'point',
  'tremend',
  'promis',

In [85]:
#check number of occurence of the word "associ" in each document
dtm.get_token_occurences('associ')

{'Dentistry00500.txt': 5.0,
 'Dentistry00502.txt': 2.0,
 'Dentistry00503.txt': 1.0,
 'Dentistry00505.txt': 1.0,
 'Dentistry00506.txt': 1.0,
 'Dentistry00512.txt': 2.0,
 'Dentistry00514.txt': 8.0,
 'Dentistry00515.txt': 4.0,
 'Dentistry00516.txt': 1.0,
 'Dentistry00518.txt': 2.0,
 'Dentistry00521.txt': 1.0,
 'Dentistry00523.txt': 7.0,
 'Dentistry00524.txt': 1.0,
 'Dentistry00525.txt': 2.0,
 'Dentistry00526.txt': 1.0,
 'Dentistry00528.txt': 3.0,
 'Dentistry00529.txt': 1.0,
 'Dentistry00530.txt': 8.0,
 'Dentistry00533.txt': 2.0,
 'Dentistry00534.txt': 1.0,
 'Dentistry00535.txt': 1.0,
 'Dentistry00536.txt': 2.0,
 'Dentistry00537.txt': 3.0,
 'Dentistry00538.txt': 2.0,
 'Dentistry00541.txt': 3.0,
 'Dentistry00542.txt': 1.0,
 'Dentistry00544.txt': 1.0,
 'Dentistry00548.txt': 4.0,
 'Dentistry00549.txt': 2.0,
 'Dentistry00550.txt': 2.0,
 'Dentistry00552.txt': 3.0,
 'Dentistry00553.txt': 2.0,
 'Dentistry00554.txt': 1.0,
 'Dentistry00555.txt': 1.0,
 'Dentistry00556.txt': 3.0,
 'Dentistry00557.txt

In [86]:
type(dtm.get_token_occurences('associ'))

dict

In [1]:
# define a function to calculate entropy given a distribution
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0
    
    p = p/sum(p)

    p = p[ p > 0 ]
    
    H = -sum(p*np.log2(p))
    
    return H

In [5]:
entropy(np.array( [12,45]))

0.7424875695421236

In [25]:
entropy( np.array( [100,60,40]))

1.4854752972273344

In [26]:
dtm.get_token_occurences('associ').values()

dict_values([5.0, 2.0, 1.0, 1.0, 1.0, 2.0, 8.0, 4.0, 1.0, 2.0, 1.0, 7.0, 1.0, 2.0, 1.0, 3.0, 1.0, 8.0, 2.0, 1.0, 1.0, 2.0, 3.0, 2.0, 3.0, 1.0, 1.0, 4.0, 2.0, 2.0, 3.0, 2.0, 1.0, 1.0, 3.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 3.0, 2.0, 2.0, 6.0, 7.0, 1.0, 2.0, 2.0, 5.0, 1.0, 3.0, 2.0, 2.0, 2.0, 4.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 2.0, 4.0, 4.0, 4.0, 1.0, 1.0, 1.0, 2.0, 3.0, 1.0, 1.0, 2.0, 9.0, 1.0, 1.0, 1.0, 4.0, 1.0, 1.0, 4.0, 2.0, 2.0, 2.0, 1.0, 1.0, 3.0, 2.0, 2.0, 3.0, 2.0, 2.0, 1.0, 1.0, 1.0, 3.0, 2.0, 2.0, 1.0, 1.0, 5.0, 1.0, 2.0, 1.0, 8.0, 3.0, 2.0, 1.0, 1.0, 2.0, 3.0, 2.0, 1.0, 2.0, 3.0, 1.0, 2.0])

In [28]:
#convert the distribution of word "associ" from dictionary values to a list
associ_dis = list(dtm.get_token_occurences('associ').values())

In [29]:
#calculate the entropy for the word "associ"
entropy(associ_dis)

6.614756031462427

In [30]:
dtm.get_token_occurences('associ').keys()

dict_keys(['Dentistry00500.txt', 'Dentistry00502.txt', 'Dentistry00503.txt', 'Dentistry00505.txt', 'Dentistry00506.txt', 'Dentistry00512.txt', 'Dentistry00514.txt', 'Dentistry00515.txt', 'Dentistry00516.txt', 'Dentistry00518.txt', 'Dentistry00521.txt', 'Dentistry00523.txt', 'Dentistry00524.txt', 'Dentistry00525.txt', 'Dentistry00526.txt', 'Dentistry00528.txt', 'Dentistry00529.txt', 'Dentistry00530.txt', 'Dentistry00533.txt', 'Dentistry00534.txt', 'Dentistry00535.txt', 'Dentistry00536.txt', 'Dentistry00537.txt', 'Dentistry00538.txt', 'Dentistry00541.txt', 'Dentistry00542.txt', 'Dentistry00544.txt', 'Dentistry00548.txt', 'Dentistry00549.txt', 'Dentistry00550.txt', 'Dentistry00552.txt', 'Dentistry00553.txt', 'Dentistry00554.txt', 'Dentistry00555.txt', 'Dentistry00556.txt', 'Dentistry00557.txt', 'Dentistry00558.txt', 'Dentistry00559.txt', 'Depression00500.txt', 'Depression00501.txt', 'Depression00505.txt', 'Depression00506.txt', 'Depression00509.txt', 'Depression00514.txt', 'Depression0051

In [31]:
#convert the documents that contain the word "associ" from dictionary keys to a list
associ_docs = list(dtm.get_token_occurences('associ').keys())

In [32]:
associ_docs

['Dentistry00500.txt',
 'Dentistry00502.txt',
 'Dentistry00503.txt',
 'Dentistry00505.txt',
 'Dentistry00506.txt',
 'Dentistry00512.txt',
 'Dentistry00514.txt',
 'Dentistry00515.txt',
 'Dentistry00516.txt',
 'Dentistry00518.txt',
 'Dentistry00521.txt',
 'Dentistry00523.txt',
 'Dentistry00524.txt',
 'Dentistry00525.txt',
 'Dentistry00526.txt',
 'Dentistry00528.txt',
 'Dentistry00529.txt',
 'Dentistry00530.txt',
 'Dentistry00533.txt',
 'Dentistry00534.txt',
 'Dentistry00535.txt',
 'Dentistry00536.txt',
 'Dentistry00537.txt',
 'Dentistry00538.txt',
 'Dentistry00541.txt',
 'Dentistry00542.txt',
 'Dentistry00544.txt',
 'Dentistry00548.txt',
 'Dentistry00549.txt',
 'Dentistry00550.txt',
 'Dentistry00552.txt',
 'Dentistry00553.txt',
 'Dentistry00554.txt',
 'Dentistry00555.txt',
 'Dentistry00556.txt',
 'Dentistry00557.txt',
 'Dentistry00558.txt',
 'Dentistry00559.txt',
 'Depression00500.txt',
 'Depression00501.txt',
 'Depression00505.txt',
 'Depression00506.txt',
 'Depression00509.txt',
 'Depr

In [33]:
associ_docs[1]

'Dentistry00502.txt'

In [44]:
#print the number of "Dentistry" documents that contain the word "associ"
sub = 'Dentistry'
count_dentistry = 0
for item in associ_docs:
    if sub in item:
        count_dentistry += 1
print(count_dentistry)

38


In [45]:
#print the number of "Depression" documents that contain the word "associ"
sub = 'Depression'
count_depression = 0
for item in associ_docs:
    if sub in item:
        count_depression += 1
print(count_depression)

22


In [46]:
#print the number of "Diabetes" documents that contain the word "associ"
sub = 'Diabetes'
count_diabetes = 0
for item in associ_docs:
    if sub in item:
        count_diabetes += 1
print(count_diabetes)

62


In [48]:
#this is an important step
#make an array, rows represent "Dentistry", "Depression", and "Diabetes" respectively. Columns represent the number of documents that contains the word "associ" and the number of documents that do NOT contain the word "associ"
array = np.reshape((count_dentistry,60-count_dentistry,count_depression,40-count_depression,count_diabetes,100-count_diabetes ),(3,2))

In [49]:
array

array([[38, 22],
       [22, 18],
       [62, 38]])

In [50]:
#calculate the column sum of the array
np.sum(array, axis = 0)

array([122,  78])

In [51]:
#calculate the row sum of the array
np.sum(array, axis = 1)

array([ 60,  40, 100])

In [53]:
#calculate the entropy of the document class (Dentistry, Depression, and Diabetes)
marginal_entropy = entropy(np.sum(array, axis = 1))

In [66]:
#calculate the column probabilities
column_probs = np.sum(array, axis = 0)/200

In [67]:
column_probs

array([0.61, 0.39])

In [77]:
#calculate the column entropies
column_entropy = np.apply_along_axis(entropy, 0, array)

In [78]:
column_entropy

array([1.46607412, 1.50864079])

In [80]:
conditional_entropy = sum(column_probs*column_entropy)

In [81]:
conditional_entropy

1.4826751237111302

In [82]:
#calculate the mutual information between the word "associ" and the document class (Dentistry, Depression, and Diabetes)
MI_associ = marginal_entropy - conditional_entropy

In [83]:
MI_associ

0.0028001735162042074